### ISSUE TITLE
Crawling exists immediately 

### ISSUE THREAD

**Issue by vgiotsas** [wiberlin/ipfs-crawler#1]
When I try to run a crawl with `./start_crawl` I get no results, the crawler just exists immediately, as shown in the output below.
I'm running it on Ubuntu 18.04.4 with go version go1.14.3

```
INFO[19:59:22] Thank you for running our IPFS Crawler!
INFO[19:59:22] Checking whether weak RSA keys are allowed...  weak_RSA_keys=true
INFO[19:59:22] Creating workers...                           numberOfWorkers=1
INFO[19:59:22] Adding cached peer to crawl queue.            amount=0
INFO[19:59:22] Starting crawl...
INFO[19:59:24] Stopping crawl...
INFO[19:59:24] Crawl finished. Summary of results.           connectable nodes=0 end time:="20-08-20--19:59:24" number of nodes=0 start time="20-08-20--19:59:22"
INFO[19:59:24] Online nodes saved in cache                   File=nodes.cache
```

**Comment by scriptkitty** [comment]
Thank you for the log @vgiotsas 
Your command to execute the crawl looks fine, FYI, the warning about weak keys is due to a discrepancy in key sizes between old versions of IPFS and libp2p. Since we want to crawl peers running old IPFS versions as well we need that env variable.

What's the output of

```du -h precomputed_hashes/preimages.csv.zst```?

If it's < 83MB, running ```git lfs pull``` (recommended) or ```make preimages``` (needs some RAM) should, hopefully, solve your problem.

**Comment by vgiotsas** [comment]
Thanks a lot @scriptkitty I solved the problem!

I had executed the `make preimages` which populates the `precomputed_hashes/preimages.csv` but doesn't produce the zst compressed file. I created the `precomputed_hashes/preimages.csv.zst` manually (after install `zstd`) and now it seems to be running. Maybe it can be useful to add these steps in the README?

By the way, the `git lfs pull` doesn't work for me
> git: 'lfs' is not a git command. See 'git --help'.

**Comment by scriptkitty** [comment]
Great to hear that it worked! :)

Our code can deal with both: a zstd-compressed file or a normal CSV, you can specify that in ```configs/config.yml``` under ```preimagepath```. The crawler decides based on the suffix: if it sees .zst it will load the preimages through zstd-lib, otherwise it just loads the .csv in text-mode.
So if you've issued ```make preimages``` you can simply point to the .csv in the config and it should work as well.

But you're definitely right: this is somewhat underspecified and overly complex at the moment -- so thanks a lot for your patience and feedback, we'll figure something out to make this easier, more streamlined and better documented.

You're also correct in that the ```git-lfs``` package is not installed as a default in Ubuntu, even if you have git installed as I just realized...
